ibm-openbmc/openpower-pel-parsers

modules/pel/datastream.py
modules/pel/peltool/comp_id.py
modules/pel/peltool/default.py
modules/pel/peltool/ext_user_data.py
modules/pel/peltool/extend_user_header.py
modules/pel/peltool/failing_mtms.py
modules/pel/peltool/imp_partition.py
modules/pel/peltool/parse_user_data.py
modules/pel/peltool/pel_types.py
modules/pel/peltool/pel_values.py
modules/pel/peltool/peltool.py
modules/pel/peltool/private_header.py
modules/pel/peltool/registry.py
modules/pel/peltool/src.py
modules/pel/peltool/user_data.py
modules/pel/peltool/user_header.py
setup.py

This is a python based PEL parser that outputs a PEL as JSON.  It uses
the same SRC and UserData plugin infrastructure as the original C++
based peltool.
It uses the 'pel_registry' module to find where the
message_registry.json and component name files are installed, though if
that isn't present, which it won't be on the BMC, it will look in the
BMC location which is /usr/share/phosphor-logging/pels/.  If it still
can't find it, it will just skip the SRC details and component names.
Invoke with:
$ python3 -m pel.peltool.peltool -f \<PEL file\>
$ python3 .../site-packages/pel/peltool/peltool.py -f \<PEL file\>
For now, it isn't installing peltool.py as a script into bin, since I
don't think I'm ready for all BMC users to know about it yet, which
they would if it was in the path along with …

Add peltool

---

modules/pel/peltool/peltool.py
modules/pel/peltool/user_header.py

Add options to peltool so it will just exit without printing anything
based on if the PEL is serviceable or not, where a serviceable PEL is
one with a severity that is neither informational or recovered.
This is for the case where a script is calling peltool on many PELs to
allow it to choose if it wants all PELs printed, or just serviceable or
nonserviceable ones.
-s: only print PEL if it's serviceable
-n: only print PEL if it's nonserviceable
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

peltool: (non)serviceable PEL skipping

---

modules/calloutparsers/ocallouts/ocallouts.py
modules/pel/peltool/pel_values.py
modules/pel/peltool/src.py

The maintenance procedures used in callouts may have a description
provided by a plugin, so attempt to load the plugin and get the
description.
The plugin would be named calloutparsers.Xcallouts.Xcallouts where X is
the creator ID of the PEL in lower case.  The function called is:
def getMaintProcDesc(procedure: str) -> str
It returns a JSON string.
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

peltool: Use procedure desc plugins

---

README.md
test/test_datastream.py
test/test_hwdiags_parserdata.py

The current instructions in the README.md requires that each test case
adds the `modules` directory to the import path. This can be avoided if
the unit test command is run from the `modules` directory.

Update unit test instructions

---

setup.py

Two data files used by the IO drawer error log plugin were moved to a
different module/directory.
Update the setup.py file so the files are installed from the new
module/directory.
Signed-off-by: Shawn McCarney <shawnmm@us.ibm.com>

IO Drawer: Update setup.py due to data file move

---

modules/pel/peltool/parse_user_data.py

The compID variable is really an integer and not a string, so fix that
in the __init__() parameter list that specifies it.
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

Fix type hint in parse_user_data.py

---

modules/udparsers/oe500/oe500.py

A new user data section was added for openpower-hw-diags where an error signature is stored within scratch registers if analysis is interrupted. This adds the parsing for that new section.
Signed-off-by: Caleb Palmer <cnpalmer@us.ibm.com>

Add parser for new error signature stored in scratch regs

---

modules/calloutparsers/ocallouts/ocallouts.py

On the IBM OpenPOWER systems, event logs and hardware isolation records are created after encountering a hardware failure. These records will be resolved once the repair action is performed. However, in certain situations, the service engineer or customer can defer the service action for some of the failures. In such cases, there are chances to miss such failure records, and the system may fail unexpectedly, causing undesirable impacts. This problem is overcome by sending periodic error events to remind about the failed parts present in the system
added new procedure that gets logged when failed parts are present in the system
Change-Id: Ifc743d6bd9441c67ff7266c55ffd094577784e35

peltool: add new procedure description for failed parts present

---

modules/pel/peltool/pel_types.py
modules/pel/peltool/src.py

Hostboot's SRCs use the same deconfig and guard flags that BMC SRCs do,
so also print them if hostboot created the SRC.
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

Print deconfg/guard flags in hostboot SRCs

---

modules/pel/hexdump.py

There are existing tools in the service area that have worked for years on the format of this tool's predecessor's hex dump format, and a request was made to have peltool use the same format so that those tools can work.
Since I don't know of any tools parsing this current format, I agreed to the change.
New format:
```
"00000000     0000000A  712A2000  000D0026  000020A7     ....q* ....&.. .",
"00000010     B0021000  02B54000  494F2D4C  43532D42     ......@.IO-LCS-B",
```
Old format:
```
"00000000:  0000000A 712A2000 000D0026 000020A7  |....q* ....&.. .|",
"00000010:  B0021000 02B54000 494F2D4C 43532D42  |......@.IO-LCS-B|",
```

Slightly modify default hexdump format

---

modules/calloutparsers/ocallouts/ocallouts.py

Fix a syntax error that was causing the callout procedure descriptions to not be displayed.

Fix JSON syntax error in procedure desc file

---

modules/pel/peltool/config.py

This class holds configuration options for peltool.
It should have been part of the previous commit but was missed.

peltool: Add Config class

---

peltool-wrapper/setup.py

The previous commit added a python module to peltool-wrapper, so bump the package version so users can upgrade peltool-wrapper and have it pull in the new occ-pel-parser-module.

peltool-wrapper: Bump version

---

modules/pel/peltool/ext_user_data.py
modules/pel/peltool/user_data.py

The UserData parsers are supposed to return a string that contains valid JSON.  If they return invalid JSON then peltool will crash with a JSON exception.
Fix that by catching the JSON exception and printing a hexdump of the data instead.
This was happening when a UserData section that contained JSON (the built in JSON created by the BMC) was truncated in a large PEL so wasn't valid.

peltool: Handle bad JSON in from UD parsers

---

modules/pel/peltool/config.py
modules/pel/peltool/pel_types.py
modules/pel/peltool/peltool.py

This commit introduces the -t/--termination option. 
Shows only pels with System Termination Critical Error. 
Can show pels based on given value
Tested on sample PEL files
Sample output:
```bash
{
"0x50005679": {
"SRC":                  "BC8A1B01",
"PLID":                 "0x50005679",
"CreatorID":            "BMC",
"Subsystem":            "HostBoot",
"Commit Time":          "04/25/2024 09:39:10",
"Sev":                  "Critical Error, System Termination",
```
Signed-off-by: harsh-agarwal1 Harsh.Agarwal@ibm.com

peltool: Add --termination option

---

modules/pel/peltool/peltool.py

This commit introduces the -r/--reverse option.
Reverses the output order for -l and -a option
Sample output:
```bash
$  python3 -m pel.peltool.peltool -p testfolder -l
{
"0x50005507": {
"SRC":                  "BD11E510",
...
$ python3 -m pel.peltool.peltool -p testfolder -l -r
{
"0x50005679": {
"SRC":                  "BC8A1B01",
...
```

peltool: Add -r option

---

setup.py

User can run peltool.py instead of long module name with the -m arg.
This will improve readability.
Tested on BMC and non-BMC system.
Sample:
```bash
$ peltool.py -h
$ python3 -m pel.peltool.peltool -h
```
Both above commands will fetch same results

peltool: Allow to run peltool without module name

---

modules/pel/peltool/peltool.py

This PR introduces the -d and -D option.
Delete a PEL based on its ID
Delete all PELs
This PR also changes older -d/--directory to -j/--json
Sample output:
```bash
$ peltool.py -j -p testpels2/ -o jsonout/
$ peltool.py -p deltest/ -d 0x50005507
$ peltool.py -p deltest/ -d 0x50005507
PEL not found
$ peltool.py -p deltest/ -D
$ peltool.py -p deltest/ -l
{}
```

peltool: Add -d and -D option

---

modules/pel/peltool/peltool.py

For BMC PELs, lEID and pLID are same, 
Not necessary for PHYP ones.
Hence, fixing eid of -l option from pLID to lEID

peltool: Fix, EID is unique for the PEL so use EID instead of PLID

---

modules/pel/peltool/peltool.py

- This commit enables peltool --archive option for BMC.
```
-A, --archive         List or display archived PELs
```
- This option is not listed on non-BMC environment
```
peltool.py: error: unrecognized arguments: --archive
```
Few example outputs:
- Incase of archive PELs present
```
python3 -m pel.peltool.peltool -l --archive
{
"0x5000599E": {
"SRC":                  "BD13E510",
"Message":              "Error Signature: 0x20da0020 0x1 0x5074001d",
"PLID":                 "0x5000599E",
"CreatorID":            "BMC",
"Subsystem":            "Processor Unit (CPU)",
"Commit Time":          "04/29/2024 08:51:09",
"Sev":                  "Unrecoverable Error",
"CompID":               "bmc hw diags"
},
```
- Incase of no archive PELs
```
python3 -m pel.peltool.peltool -l --archive
{}
```
- …

Add --archive peltool option for BMC

---

modules/pel/peltool/peltool.py

-e option is no more limited to -d option.
Therefore changing help, to avoid potential confusion

peltool: Refined help function of -e option

---

modules/pel/peltool/config.py
modules/pel/peltool/pel_values.py
modules/pel/peltool/peltool.py

This commit introduces the -S/--severity option.
Using this option we can filter by severity. 
We consider pels matching the provided category only.
Sample output:
```bash
$ peltool.py -p testpels/ -l -S Unrecoverable Predictive
{
"0x50000BE1": {
"SRC":                  "BD554002",
"PLID":                 "0x50000BE1",
"CreatorID":            "BMC",
"Subsystem":            "CEC Hardware - VPD Interface",
"Commit Time":          "06/11/2024 18:05:03",
"Sev":                  "Predictive Error",
...
$ peltool.py -p testpels/ -l -S Unrecoverable
{
"0x900001EB": {
"SRC":                  "BC8A2BC0",
"PLID":                 "0x900001EB",
"CreatorID":            "Hostboot",
"Subsystem":            "HostBoot",
"Commit Time":          "06/11/2024 18:06:31",
"Sev": …
```

peltool: Add -S option

---

modules/pel/peltool/peltool.py

Using help section, the current --severities option description is large. 
Reducing option description size.
-S section in current help output
```bash
-S {Informational,Recovered,Predictive,Unrecoverable,Critical,Diagnostic,Symptom} [{Informational,Recovered,Predictive,Unrecoverable,Critical,Diagnostic,Symptom} ...], --severities {Informational,Recovered,Predictive,Unrecoverable,Critical,Diagnostic,Symptom} [{Informational,Recovered,Predictive,Unrecoverable,Critical,Diagnostic,Symptom} ...]
Filter by severity value, consider pels matching the provided severities. ['Informational',
'Recovered', 'Predictive', 'Unrecoverable', 'Critical', 'Diagnostic', 'Symptom']
```
-S section help output after this commit
```bash
-S SEVERITIES, --severities SEVERITIES
Filter by severity value, consider …
```

peltool: Fix, long --severities option description

---

modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

- This commit enables peltool -x/--hex option.
```
-x, --hex             Display PEL(s) in hexdump instead of JSON
```
- Sample output
Note: A line separator 'PEL Begin' and 'PEL End' is added before and after displaying pel in hexdecimal format.
```
-------------- PEL Begin  ----------------
00000000     50480030  0100526D  20250625  06414000     PH.0..Rm %.%.A@.
00000010     20250625  06421106  48000006  000001E3      %.%.B..H.......
00000020     00000000  00000000  82000C22  5000805C     ..........."P..\
00000030     55480018  01004552  82030001  00000000     UH....ER........
00000040     00002000  00000003  50530050  01004552     .. .....PS.P..ER
00000050     02000009  00000048  30000000  00000000     .......H0.......
00000060     00000000  00000000  00000000  00000000 …
```

Add -x/--hex peltool option

---

modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

This commit moves extension string argument in config file.
Tested the changes with following options
```
peltool.py -p pel-parser -e .pel -l
peltool.py -p pel-parser -e .pel -n
peltool.py -p pel-parser -e .txt -a
peltool.py -p pel-parser -e .txt -a -x
peltool.py -p pel-parser -e .pel -l -r
```

Add extension option in config file

---

modules/pel/peltool/config.py
modules/pel/peltool/pel_types.py
modules/pel/peltool/peltool.py
modules/pel/peltool/user_header.py

Changed the definition of serviceable PEL to the official definition. 
Created a function to check if the PEL is hidden.
Patch above [PR57](https://github.com/ibm-openbmc/openpower-pel-parsers/pull/57)

peltool: Fix, Definition of serviceable and Add -O

---

modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

Implement --plid and --src option
- --plid option displays PELs matched with given Platform Log ID and
--src displays PELs matched with given System Reference code from
the overall serviceable,non-serviceable, hidden PELs
```
--plid PLID           Display PELs based on its Platform Log ID
--src SRC             Display PELs based on its System Reference Code 
```
- Tested changes on BMC environment.
-  Sample output with --plid option
```
> python3 peltool.py --plid 8900006F
{
"0x8900006F": {
"SRC":                  "BC13E504",
"PLID":                 "0x8900006F",
"CreatorID":            "Hostboot",
"Subsystem":            "Processor Unit (CPU)",
"Commit Time":          "07/12/2025 05:24:35",
"Sev":                  "Recovered Error",
"CompID":               "hostboot: prdf"
}
}
> python3 …
```

Add --plid and --src option

---

modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

When using -i or --bmc-id option
for Non-Serviceable/Hidden PELs there was empty output
Sample output Before update:
```bash
$ peltool.py -p testpels/ -i 0x50000BF3
```
Sample output After update:
```bash
$ peltool.py -p testpels/ -i 0x50000BF3
{
"Private Header": {
"Section Version":           1,
"Sub-section type":          0,
"Created by":                "1000",
...
```

peltool: Fix, Get NonServiceable PEL by --id/--bmc-id

---

modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

Implement --src-exclude option
```
-src-exclude SRC_EXCLUDE_FILE    Display PELs excluding SRCs from the file
```
- Tested changes on BMC environment.
- Sample src_exclude_file file
- src_exclude_file supports any format, few examples are mentioned below.
```
>cat src_exclude_file
BC20E504B7006A26
BC13E504
>cat src_exclude_file
BC20E504, B7006A26, BC13E504
>cat src_exclude_file
BC20E504, B7006A26
BC13E504
>cat src_exclude_file
BC20E504 B7006A26 BC13E504
```
```
python3 peltool.py --src-exclude ~/src_exclude
{
"0x500082DB": {
"SRC":                  "110015F0",
"Message":              "A power supply has indicated an input or under voltage condition.",
"PLID":                 "0x500082DB",
"CreatorID":            "BMC",
"Subsystem":            "Power Supply",
"Commit Time": …
```

Add --src-exclude option

---

README.md
modules/pel/peltool/README.md

- This commit improvises the README.md for peltool.
- Also, new modules/pel/peltool/README.md is added to showcase
legacy and new peltool commands usage.

Add README.md for peltool parser

---

modules/pel/peltool/pel_values.py

Defined new entry in PEL values action flags field to incorporate 
updated PEL spec error action flag bit#10.
Tested:
Sample output:
Old:
```bash
python3 -m pel.peltool.peltool -f 2024092414360909_500055AC
...
"Action Flags": [
"Report Externally"
],
...
```
New:
```bash
"Action Flags": [
"Report Externally",
"Heartbeat Call Home Event"
],
```
Signed-off-by: Harsh Agarwal Harsh.Agarwal@ibm.com

Peltool: Added new action flag value

---

modules/pel/peltool/comp_id.py
modules/pel/peltool/parse_user_data.py
modules/pel/peltool/peltool.py
modules/pel/peltool/src.py
modules/srcparsers/osrc/osrc.py

Enhances performance of -a option by printing as soon as each PEL 
is parsed. 
This change minimizes the overhead associated with storing and 
processing large strings, resulting in faster output generation.
Tested Non-BMC env:
```bash
time python3 -m pel.peltool.peltool -a -p 3kpels/
1m3.707s    ->  0m38.749s
```
Optimize performance by implementing caching mechanisms for
component IDs, user data parsers, callout parsers, and SRC
modules.
These changes reduce redundant module imports by storing previously
loaded modules in dictionaries, streamlining the parsing process
and enhancing overall efficiency.
Tested:
```bash
Non-BMC env:
-n: 0.941s    ->  0.283s
-l: 6.100s    ->  4.225s
-a: 52.740s   ->  17.371s
BMC env:
-n: 4.287s   ->  4.217s
-l: 1m24.911s ->  14.125s
-a: 1m37.431s -> …
```

Peltool: Performance improvement

---

modules/pel/peltool/README.md
modules/pel/peltool/config.py
modules/pel/peltool/peltool.py

This commit introduces the -E/--every-pel option.
We consider all the pels in the default/specified folder.
Sample output:
```bash
$ peltool.py -p tpels/ -n
{
"Number of PELs found": 7
}
$ peltool.py -p tpels/ -En
{
"Number of PELs found": 13
}
```

Peltool: Add -E/--every-pel option

---

modules/pel/peltool/peltool.py

This commit add log message for -D/--delete-all option
Sample output:
```bash
$ peltool.py -D
```
In Journalctl we would see:
```bash
peltool deleting all event logs
```

Peltool: Add log for -D option

---

modules/pel/peltool/peltool.py

This commit updates the behavior of -f/--file option. 
Previously, certain PEL files were ignored due to the default behavior.
With this change, we consider any PEL file passed to it.
Sample output:
```bash
$ peltool.py -f tpels/2022031117260306_89000119
$ peltool.py -f tpels/2022031117260306_89000119
{
"Private Header": {
"Section Version":           1,
...
```

peltool: Modify -f option

---

modules/pel/hwdiags/parserdata.py

In the PEL parser signature description, the model_ec value will be used instead of the chip description to avoid exposing internal keywords.

openpower-hw-diags: avoid using internal keywords
